### PR TITLE
Document installation of djangoajax

### PR DESCRIPTION
**Pull request by jmewes**

### CODE REVIEW

**Comment by jmewes** [comment]
See 9c6a5fad8b46e851a7734d1408d36e1bdd187395

**Comment by Doca** [comment]
why should this be in the docs if it's in requirements?

**Comment by jmewes** [comment]
@Doca Because I spend 30 minutes figuring out why I cannot run the app anymore

**Comment by Doca** [comment]
hmm mabe i forgot to put it there?! But now its in right?

**Comment by jmewes** [comment]
My scenario was like this
1. install the development version of the Volunteer Planner like explained in the README
2. work on a feature branch
3. merge current changes from the "development" branch into the feature branch
4. wondering about the ajax error message
5. run pip install like in cb27d2ad9860977fe9e3437ab14ce971209ea211

Yes, now everything works out. The requirement has been declared in the file `requirements/_base.txt
` with 9c6a5fad8b46e851a7734d1408d36e1bdd187395 . So maybe nobody with a fresh setup will run into this.

**Pull request closed without merging**
