### PR TITLE
Refine docker usage

### PR DESCRIPTION
**Pull request by pitpalme**
Modified Dockerfile to create a little more sophisticated image,
consuming less space and without image recreation on application code
change. Application code is linked as volume and django's autoreload
feature will update the running process.
As neither the image nor the container are supposed to be given to
someone else there's no need to add our source code.

Additionally service creation has been refined, to
- reflect new compose file version ("2")
- use a data volume that is kept even if DB container is accidentally
  deleted (needs some tweaking for PostgreSQL!)
- sets limits, just to be sure, we're not exhausting beyond all limits
- use 'entrypoint' and 'cmd' in a reasonable way, to make
  'docker-compose' usage easier to use for initialization

### CODE REVIEW

**Comment by pitpalme** [comment]
@klinger Hello, could you evaluate, if it still works for you? I thought about moving this "yet dev only" feature towards a direction, that in a far, far future might allow us to use it more versatile (thinking about beta, qs, etc, ...).

**Comment by klinger** [comment]
A major change in docker - nice work!

Some remarks:

a) Could     

> cap_add:
>       - ALL
> cap_drop:
>       - NET_ADMIN
>       - SYS_ADMIN
>       - NET_RAW
>       - SYS_PTRACE
>       - SYS_TIME

be changed to 

> cap_drop:
>       - NET_RAW

--> Why this explicit statement here? Which of the capabilities in ALL do we need as addition to the default capabilites? 

b) I would prefer it built on smaller images like kiasaki/alpine-postgres - but this would require some work.

c) mysql doesnt work out of the box because the connection from the ip of web is not allowed to connect to the mysql database.

> django.db.utils.OperationalError: (2003, 'Can\'t connect to MySQL server on \'db\' (111 "Connection refused")')


d) postgres fails to build:

> /bin/sh: /bin/tmp: not found --> This should be /bin/rm

> ERROR: Service 'web' failed to build: The command '/bin/sh -c apk update && apk add musl-dev postgresql postgresql-dev gcc &&     pip install -r dev_postgres.txt &&     apk del --purge gcc musl-dev &&     /bin/tmp -rf /var/cache/apk/*' returned a non-zero code: 127

e) The data volume has only the mysql path.

f) I did try this with outcommented volumes - as I dont have a VP mysql/postgres yet

**Comment by klinger** [comment]
I have timing issues - the db containers take too long time to get ready.

```
depends_on:
      - db
```
in the web container helps a bit.

If I start them separately by

> 
> docker-compose up deb
> docker-compose up web

everything is fine.

**Comment by pitpalme** [comment]
a) Solved. Leftover from playing with capabilities. Useless and therefore removed
b) Done.
c) Ignored.
d) Solved. As there's only one multi-client-enabled image left the typo disappeared completely
e) Unluckily. Doesn't work different, unless much effort is put into creating own docker images for both intended DB systems.
g) 
```bash
docker inspect -f '{{range $name, $settings := .NetworkSettings.Networks}}{{$name}}{{end}}' volunteer_db_1 volunteer_web_1
docker network ls -f 'name=volunteer_default'
```
h) timing issue taken a little care of, but: [Note for 'depends_on'](https://docs.docker.com/compose/compose-file/#depends-on)

**Comment by klinger** [comment]
like it, it works ;-)

**Pull request merged**
