### PR TITLE
Feature/map view

### PR DESCRIPTION
**Pull request by XComp**
I replaced the old location overview by a map. I haven't worked on the CSS part so far since I thought that there is a refactoring of the page in the pipeline anyway.

Currently, it's required by all locations to have a geo position. Otherwise, the location wouldn't be displayed.

### CODE REVIEW

**Comment by XComp** [comment]
I added a Json endpoint for retrieving the location data that shall be displayed under the map view. The data is then requested using jQuery. Therefore I added the DjangoRestless and py (which was automatically added) to the pip dependency list under requirements/_base.txt. Hence, don't forget to install the new dependencies.

**Comment by maikhoepfel** [comment]
@christophmeissner What's the state of this? I'm not sure I know what "later" means. Shall I review or not?

**Comment by christophmeissner** [comment]
Please review, @maikhoepfel. Thanks.

**Comment by maikhoepfel** [comment]
Lovely, looks pretty cool and is usable. Thanks for that!

image

I think we've decided that we'll switch to Django REST Framework for our REST needs, but that's only a small change. We'll pick this up when the new shift planner landed; that's unfortunately a higher priority at the moment. But this PR won't age too quickly, because it's mostly JS.

**Comment by XComp** [comment]
I added a HEREMap class. Sample code of how to use the class are added to the end of map.js. This class makes it easier to reuse the map. It can be used to create the map, add markers, set the initial view port based on markers and define a callback method that gets called if a marker was clicked. The colors of the markers also change if one was clicked.

**Comment by XComp** [comment]
The map view is now integrated. It is drawn on top of the facility listing. There's currently no event listener registered that would be triggered when clicking on a marker. But the code is now in a state where I would think that it's worth reviewing the feature again.
facility_map

**Comment by klinger** [comment]
We have to decide which way to follow: This one here or #297 or something else. 

I personally prefer a lightweight representation (leaflet) - and free and non-commercial maps (openstreetmap.org). This here is quite a lot of code for "just some dots on a map". I will later inspect the code (i thought putting the shelters on the map with a short description and a link to a django site should be only a few lines of code).

Is it possible to change this map to openstreetmap? There are lots of user agreements for HERE maps - and it may be expansive later if we have to pay if our project may not be part of "personal use" anymore. And: HERE would dishonor our advertising-free guarantee.

**Comment by leodabbler** [comment]
I also would encourage to use free software as well as data whenever
possible

Am 07.12.2015 um 18:54 schrieb Soenke Klinger:
> Is it possible to change this map to openstreetmap? There are lots of
> user agreements for HERE maps - and it may be expansive later if we
> have to pay if our project may not be part of "personal use" anymore.
> And: HERE would dishonor our advertising-free guarantee.

**Pull request closed without merging**
