### PR TITLE
Open maps with OSM

### LINKED ISSUE #329: Using OpenStreetMap
Have you considered switching to OSM? I think that from an ethical point of view it makes a lot more sense, but I have no direct experience with their API.

Would love to help, in case you decide to switch.

### PR DESCRIPTION
**Pull request by asymmetric**
Instead of pointing to google maps, point to OSM. Due to the way OSM
works, the user is required to click on the result that best matches the
query - OSM doesn't do that, unlike Google Maps.

Some addresses (e.g. "Wrangelstraße 98/Zeughofstraße 24" for "NUK Wrangelstraße") don't make any sense to OSM, and thus won't return any results until the user cleans up the query.

**NOTE**: This is my absolute first time writing Python code so please review thoroughly! :pray: 

Closes #329.

### CODE REVIEW

**Comment by klinger** [comment]
Wow - didnt think this would so few lines of codes to change it. Just a small new Django app. I like it. 
The disfunct adresses we can ignore in working on issue #329 .

A first review:

A) It works on my machine too.

B) Is there a reason you didnt change organizations/templates/facility.html "google maps" into "osm maps"?

C) Is there a reason  you didnt remove /volunteer_planner/google_tools/templatetags and the two files in it? If its not used anymore we can just remove it from the active codebase. Its in git if it is ever needed again.

You may just add another commit to your PR.

**Comment by asymmetric** [comment]
Fixed A and B. Thanks for reviewing!

**Comment by asymmetric** [comment]
Is there any info on if/when this could get merged?

**Comment by klinger** [comment]
Sorry could jave told you this before. We meet in an hour and want to merge it today. Maybe even deploy it today.

**Pull request merged**
