### PR TITLE
Shiftmailer statistics

### PR DESCRIPTION
**Pull request by leodabbler**
- separated Excel rendering from mailing
- implemented statistics as explained in issue #343

### CODE REVIEW

**Comment by klinger** [comment]
Looks very nice here, but we need to review it thoroughly. (I will do it soon, anybody else too?)

**Comment by leodabbler** [comment]
I'm currently reworking it a little. Thus, feel free to merge or wait.

**Comment by klinger** [comment]
def get_sheet(wb, name, header=None, footer=None):
def write_user_line(ws, cur, i, volunteer, style):

are only used in class ExcelRenderer:

so maybe refactor them too?

**Comment by leodabbler** [comment]
How do you want them to be refactored? I haven't changed them so far. Do you want to inline them (replacing the calls to them)? I wouldn't do that, as each of these functions has a pretty clear responsibility.

**Comment by leodabbler** [comment]
Commit 907d427 contains a new unit test that already might be useful for you. It calls the excel renderer with fixed test data and writes the results to the temporary test folder provided by pytest's  tmpdir fixture (usually like /tmp/pytest-3/...).
However, this test is still in progress and doesn't contain assertions so far.

**Comment by klinger** [comment]
I thought about inlining the methods into the class (static methods?) - they are so free floating outside, arent they?

**Comment by leodabbler** [comment]
Already done, contained in next push

**Comment by leodabbler** [comment]
I have provided this pull request 6 weeks ago, please check it and issue #343

**Comment by klinger** [comment]
Tests of mailer have been successful.

Changes merged into develop branch.

**Pull request closed without merging**
